### ISSUE TITLE
Change the department of an employee: setdepartment

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#123]
**Describe the bug**
There is a bug in the user guide section 3.2.4, where if i type in setdepartment 1 d/Junior Management d/Senior Management, the latest department will be set, which in this case is senior management. However, the user guide did not state the fact that only the latest department will be taken if the user decides to type in multiple departments.

**To Reproduce**
1. setdepartment 1 d/Junior Management d/Senior Management

**Expected behavior**
I expected the department of the person at index 1 to be set at junior management, however it instead is set at senior management.

**Screenshots**
![capture](https://user-images.githubusercontent.com/22737907/47906051-64724700-dec3-11e8-9ad7-ef864e5807f1.PNG)

<hr>

**Reported by:** @chocological
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#575]</sub>

**Comment by Woonhian** [comment]
Hi, 
Thank you for reporting this. First of all the screenshot you have provided does not match with the bug report.

Back to the bug report, the stated command in your description does not conform to the command format shown in the user guide.
![image](https://user-images.githubusercontent.com/35731563/47933581-ea1be400-df0f-11e8-8b4f-cf143b18ed99.png)
But since user may have "accidentally" keyed in 2 prefixes, I decided to reject the command and it is completed in the PR #129 .
![image](https://user-images.githubusercontent.com/35731563/47933911-dc1a9300-df10-11e8-8ad1-3edacd2a82b6.png)
Thank you for the report and look forward for our latest product, BankAB v1.4!
