### ISSUE TITLE
Command Leave application : leave

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#127]
**Describe the bug**
There is a bug in the user guide section 3.3.1, where if i type in leave date/20/11/2019 date/20/11/2020, only the latest leave date will be taken, instead of the first date of 20/11/2019. However, the user guide did not state the fact that only the latest leave date will be taken, and not the previous leave dates.

**To Reproduce**
1. type in leave date/20/11/2019 date/20/11/2020

**Expected behavior**
I expected the first date to be taken instead, since the user guide did not explicitly say which of the two dates will be taken.

<hr>

**Reported by:** @chocological
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#679]</sub>

**Comment by Hafizuddin-github** [comment]
Hi, first of all the input command is in a **wrong format**. 

See screenshot below: 
<img width="444" alt="screenshot 2018-11-05 at 2 07 22 pm" src="https://user-images.githubusercontent.com/35729747/47980769-231caa00-e104-11e8-80b0-5cd3342b227a.png">

But since user may have "accidentally" keyed in 2 prefixes, I decided to reject the command and it is completed in the PR #132 .
<img width="444" alt="screenshot 2018-11-05 at 2 08 22 pm" src="https://user-images.githubusercontent.com/35729747/47980811-46dff000-e104-11e8-8b7a-8d709cbe6478.png">

Thank you for reporting!
