### ISSUE TITLE
Start time can be later than end time

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#128]
**Please describe the problem**
using setschedule ,we can set start time later than end time

**Describe the improvement you'd like to suggest**
It is not logically correct

**Additional context**
![image](https://user-images.githubusercontent.com/32838530/47908450-33e0dc00-dec8-11e8-9467-478c70ec5d87.png)

<hr>

**Reported by:** @liu-tianhang
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#701]</sub>

**Comment by speezy37** [comment]
Hi,
This function is working as intended.

We created this app as a workflow platform for all employees working in a banking environment. While many do not realize this, it includes security guards, as well as employee from IT department working overtime.

Hence, in this scenario, the person you created has a daily schedule of working in the `Toilet` from 2300 hours (11 pm) to 1000 hours (10 am) of the following day.

I understand that you may think that this is a logical error since we did not specifically state that end time could be in the following day. We will try to fix it in the next version.

Look forward for our latest product, BankAB v1.4!
